services:
  calendar:
    build:
      context: ../
      dockerfile: deployments/build/Dockerfile
    container_name: calendar_service
    volumes:
      - ../configs:/app/configs
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/app/configs/config.yaml
      - DATABASE_URL=postgres://user:password@db:5432/calendar
    networks:
      - calendar_network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calendar
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - calendar_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 2s
      timeout: 3s
      retries: 5

networks:
  calendar_network:
    driver: bridge
    name: calendar_network

volumes:
  db_data:
    driver: local