version: '3.8'

services:
  calendar:
    build:
      context: ./build
    container_name: calendar_service
    volumes:
      - ../configs:/app/configs # Монтирование конфигураций из локальной директории
    ports:
      - "8080:8080"
    environment:
      - CONFIG_PATH=/app/configs/config.toml # Путь к конфигурационному файлу
    networks:
      calendar_network:
        aliases:
          - calendar
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: calendar
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      calendar_network:
        aliases:
          - database

networks:
  calendar_network:
    driver: bridge
