[logger]
# Уровень детализации логирования, может быть: "debug", "info", "warn", "error"
level = "debug"

[db]
# Параметры подключения к базе данных
host = "localhost"
port = 5432
user = "your_username"
password = "your_password"
dbname = "your_dbname"

[server]
# Настройки HTTP сервера
port = 8080