name: Otus homework tests

on:
  push:
    branches:
      - hw*

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'calendar') }}
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ~1.22

      - name: Check out code
        uses: actions/checkout@v3

      - name: Linters
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.61
          working-directory: ${{ env.BRANCH }}

  tests:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'calendar') }}
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q check_running"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.22

      - name: Check out code
        uses: actions/checkout@v3

      - name: Wait for RabbitMQ to be ready
        run: |
          for i in {1..30}; do 
            nc -z localhost 5672 && break || sleep 1
          done

      - name: Check RabbitMQ connectivity
        run: |
          for i in {1..30}; do
            if nc -z localhost 5672; then
              echo "RabbitMQ is ready"
              break
            else
              echo "Waiting for RabbitMQ..."
              sleep 1
            fi
          done

      - name: Unit tests
        run: go test -v -count=1 -race -timeout=1m ./...
        working-directory: ${{ env.BRANCH }}

      - name: Optimization tests
        run: go test -v -count=1 -timeout=1m -tags bench ./...
        if: env.BRANCH == 'hw10_program_optimization'
        working-directory: ${{ env.BRANCH }}

      - name: Bash tests
        shell: bash
        run: ./test.sh
        if: contains('hw01_hello_otus hw07_file_copying hw08_envdir_tool hw11_telnet_client', env.BRANCH)
        working-directory: ${{ env.BRANCH }}

      - name: Run bash command
        shell: bash
        run: |
          echo $TEST_VAR
        working-directory: ${{ env.BRANCH }}

  tests_by_makefile:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'calendar')
    services:
      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q check_running"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.22

      - name: Check out code
        uses: actions/checkout@v3

      - name: make lint
        run: make lint
        working-directory: hw12_13_14_15_calendar

      - name: make build
        run: make build
        working-directory: hw12_13_14_15_calendar

      - name: make test
        run: make test
        working-directory: hw12_13_14_15_calendar
